### ISSUE TITLE
Error git: command not found

### ISSUE THREAD

**Issue by dinbtechit** [adrienrn/osclass-vagrant#17]
C:\Users\SrinivD1\Desktop\vagrantvms\osclass-vagrant-adrienrn [master +0 ~1 -0]> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puphpet/ubuntu1404-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: Setting the name of the VM: osclass-vagrant-adrienrn_default_1458577049712_23941
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/SrinivD1/Desktop/vagrantvms/osclass-vagrant-adrienrn
    default: /tmp/vagrant-puppet/modules-d4778c5c1e3157b685e80703a7058ff0 => C:/Users/SrinivD1/Desktop/vagrantvms/osclas
s-vagrant-adrienrn/puppet/modules
    default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => C:/Users/SrinivD1/Desktop/vagrantvms/oscl
ass-vagrant-adrienrn/puppet/manifests
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Saving local git username to VM...
**==> default: -bash: git: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.**

**Comment by adrienrn** [comment]
Hello there,

My osclass-vagrant is still a work in progress and still tailored to my suits.

Reading your log, it seems your host (PC) is missing git installed. Try to install it on your machine and relaunch.

We make some test if you have a `.gitconfig` in your home directory, we assume that git is installed. Oddly, that's not the case for you.

`==> default: -bash: git: command not found`

If you don't need git, you probably can comment some line in Vagrantfile around line 89 to 96.

Don't hesitate to submit a PR.

**Comment by dinbtechit** [comment]
Thank you so much for your quick response. I do have git installed in my machine. I think the bash is not able to recognize as I am running it on my windows machine. Let me try it on my linux machine. :)

**Comment by dinbtechit** [comment]
After commenting the line 89 to 96 from Vagrantfile, I am getting the following error this time.. :(

SrinivD1@CA-SRINIVD1  ~/Desktop/vagrantvms/osclass-vagrant-adrienrn (master)
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puphpet/ubuntu1404-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: Setting the name of the VM: osclass-vagrant-adrienrn_default_1458582460417_92496
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/SrinivD1/Desktop/vagrantvms/osclass-vagrant-adrienrn
    default: /tmp/vagrant-puppet/modules-d4778c5c1e3157b685e80703a7058ff0 => C:/Users/SrinivD1/Desktop/vagrantvms/osclas
s-vagrant-adrienrn/puppet/modules
    default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => C:/Users/SrinivD1/Desktop/vagrantvms/oscl
ass-vagrant-adrienrn/puppet/manifests
==> default: Running provisioner: puppet...
==> default: Running Puppet with site.pp...
**==> default: Error: Could not parse application options: invalid option: --manifestdir**
**The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.**

**Comment by adrienrn** [comment]
Should be fixed in #18
