### ISSUE TITLE
Install phpmyadmin

### ISSUE THREAD

**Issue by adrienrn** [adrienrn/osclass-vagrant#4]
https://github.com/justicel/puppet-phpmyadmin

---

Trying to using it triggers errors:

```
class { 'phpmyadmin': }
phpmyadmin::server{ 'default': }
```

```
==> default: Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored on line 66 in file /tmp/vagrant-puppet/modules-3966b6ceeea43eb8deca69648c846790/phpmyadmin/manifests/server.pp
==> default: Warning: Not collecting exported resources without storeconfigs
==> default: Warning: Not collecting exported resources without storeconfigs
==> default: Warning: Not collecting exported resources without storeconfigs
```

**Comment by adrienrn** [comment]
Installing the phpmyadmin package does not work.
- Need to run manually `dpkg-reconfigure phpmyadmin`
- Need to manually set the root password (see https://github.com/adrienrn/osclass-vagrant/issues/2)

**Comment by adrienrn** [comment]
First fix. for php5-mcrypt.
https://github.com/adrienrn/osclass-vagrant/commit/5faf8e9f1e944eebb615d09d47b1b734e1871891

**Comment by adrienrn** [comment]
phpmyadmin works.
Connect via `http://osclass.dev/phpmyadmin/` and hello/hello.

**Comment by tremblaysimon** [comment]
What did you do to avoid warning messages?
